import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ThemeProviderAntd } from "@repo/ui";
import type { Metadata } from "next";
import { AuthGuard } from "../../../packages/auth/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body style={{ margin: 0 }}>
        <AntdRegistry>
          <ThemeProviderAntd>
            <AuthGuard>{children}</AuthGuard>
          </ThemeProviderAntd>
        </AntdRegistry>
      </body>
    </html>
  );
}
