import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ThemeProviderAntd } from "@repo/ui";
import { AdminGuard, AuthGuard } from "@repo/auth/components";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <AntdRegistry>
          <ThemeProviderAntd>
            <AuthGuard>
              <AdminGuard>{children}</AdminGuard>
            </AuthGuard>
          </ThemeProviderAntd>
        </AntdRegistry>
      </body>
    </html>
  );
}
